// Code generated by re2go 4.1, DO NOT EDIT.
package re2go

// TODO: check "août"
// PYTHON NAME: LONG_TEXT_PATTERN
// Given the following pattern:
//
// - day: [0-3]?[0-9]
// - year: 199[0-9]|20[0-3][0-9]
// - month: January?|February?|March|A[pv]ril|Ma[iy]|Jun[ei]|Jul[iy]|August|September|O[ck]tober|November|De[csz]ember|Jan|Feb|M[aä]r|Apr|Jun|Jul|Aug|Sep|O[ck]t|Nov|De[cz]|Januari|Februari|Maret|Mei|Agustus|Jänner|Feber|März|janvier|février|mars|juin|juillet|aout|septembre|octobre|novembre|décembre|Ocak|Şubat|Mart|Nisan|Mayıs|Haziran|Temmuz|Ağustos|Eylül|Ekim|Kasım|Aralık|Oca|Şub|Mar|Nis|Haz|Tem|Ağu|Eyl|Eki|Kas|Ara
//
// It's combined into two patterns:
//
// - MDY = ({rxMonth})[\t\n\f\r ]({rxDay})(!st|nd|rd|th)?,?[\t\n\f\r ]({rxYear})
// - DMY = ({rxDay})(!st|nd|rd|th|[.])?[\t\n\f\r ](!of[\t\n\f\r ])?({rxMonth})[,.]?[\t\n\f\r ]({rxYear})
func FindLongTextPattern(input string) (year, month, day string, ok bool) {
	var cursor, marker int
	input += string(rune(0)) // add terminating null
	limit := len(input) - 1  // limit points at the terminating null
	_ = marker

	// Variable for capturing parentheses (twice the number of groups).
	const YYMAXNMATCH = 4

	yypmatch := make([]int, YYMAXNMATCH*2)
	var yynmatch int
	_ = yynmatch

	// Autogenerated tag variables used by the lexer to track tag values.
	var yyt1 int
	_ = yyt1
	var yyt2 int
	_ = yyt2
	var yyt3 int
	_ = yyt3
	var yyt4 int
	_ = yyt4

	for {
		{
			var yych byte
			yych = input[cursor]
			switch yych {
			case '0', '1', '2', '3':
				yyt1 = cursor
				goto yy3
			case '4', '5', '6', '7', '8', '9':
				yyt1 = cursor
				goto yy4
			case 'A':
				fallthrough
			case 'a':
				yyt1 = cursor
				goto yy5
			case 'D':
				fallthrough
			case 'd':
				yyt1 = cursor
				goto yy6
			case 'E':
				fallthrough
			case 'e':
				yyt1 = cursor
				goto yy7
			case 'F':
				fallthrough
			case 'f':
				yyt1 = cursor
				goto yy8
			case 'H':
				fallthrough
			case 'h':
				yyt1 = cursor
				goto yy9
			case 'J':
				fallthrough
			case 'j':
				yyt1 = cursor
				goto yy10
			case 'K':
				fallthrough
			case 'k':
				yyt1 = cursor
				goto yy11
			case 'M':
				fallthrough
			case 'm':
				yyt1 = cursor
				goto yy12
			case 'N':
				fallthrough
			case 'n':
				yyt1 = cursor
				goto yy13
			case 'O':
				fallthrough
			case 'o':
				yyt1 = cursor
				goto yy14
			case 'S':
				fallthrough
			case 's':
				yyt1 = cursor
				goto yy15
			case 'T':
				fallthrough
			case 't':
				yyt1 = cursor
				goto yy16
			case 0xC5:
				yyt1 = cursor
				goto yy17
			default:
				if limit <= cursor {
					goto yy274
				}
				goto yy1
			}
		yy1:
			cursor++
		yy2:
			{
				continue
			}
		yy3:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt2 = cursor
				goto yy18
			case '.':
				yyt2 = cursor
				goto yy20
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy21
			case 'N':
				fallthrough
			case 'R':
				fallthrough
			case 'n':
				fallthrough
			case 'r':
				yyt2 = cursor
				goto yy22
			case 'S':
				fallthrough
			case 's':
				yyt2 = cursor
				goto yy23
			case 'T':
				fallthrough
			case 't':
				yyt2 = cursor
				goto yy24
			default:
				goto yy2
			}
		yy4:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt2 = cursor
				goto yy18
			case '.':
				yyt2 = cursor
				goto yy20
			case 'N':
				fallthrough
			case 'R':
				fallthrough
			case 'n':
				fallthrough
			case 'r':
				yyt2 = cursor
				goto yy22
			case 'S':
				fallthrough
			case 's':
				yyt2 = cursor
				goto yy23
			case 'T':
				fallthrough
			case 't':
				yyt2 = cursor
				goto yy24
			default:
				goto yy2
			}
		yy5:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'G':
				fallthrough
			case 'g':
				goto yy25
			case 'O':
				fallthrough
			case 'o':
				goto yy26
			case 'P':
				fallthrough
			case 'p':
				goto yy27
			case 'R':
				fallthrough
			case 'r':
				goto yy28
			case 'U':
				fallthrough
			case 'u':
				goto yy29
			case 'V':
				fallthrough
			case 'v':
				goto yy30
			case 0xC4:
				goto yy31
			default:
				goto yy2
			}
		yy6:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy32
			case 0xC3:
				goto yy33
			default:
				goto yy2
			}
		yy7:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'K':
				fallthrough
			case 'k':
				goto yy34
			case 'Y':
				fallthrough
			case 'y':
				goto yy35
			default:
				goto yy2
			}
		yy8:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy36
			case 0xC3:
				goto yy37
			default:
				goto yy2
			}
		yy9:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy38
			default:
				goto yy2
			}
		yy10:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy39
			case 'U':
				fallthrough
			case 'u':
				goto yy40
			case 0xC3:
				goto yy41
			default:
				goto yy2
			}
		yy11:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy42
			default:
				goto yy2
			}
		yy12:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy43
			case 'E':
				fallthrough
			case 'e':
				goto yy44
			case 0xC3:
				goto yy45
			default:
				goto yy2
			}
		yy13:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy46
			case 'O':
				fallthrough
			case 'o':
				goto yy47
			default:
				goto yy2
			}
		yy14:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy48
			case 'K':
				fallthrough
			case 'k':
				goto yy49
			default:
				goto yy2
			}
		yy15:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy50
			default:
				goto yy2
			}
		yy16:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy51
			default:
				goto yy2
			}
		yy17:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 0x9E, 0x9F:
				goto yy52
			default:
				goto yy2
			}
		yy18:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				yyt4 = cursor
				goto yy53
			case 'D':
				fallthrough
			case 'd':
				yyt4 = cursor
				goto yy54
			case 'E':
				fallthrough
			case 'e':
				yyt4 = cursor
				goto yy55
			case 'F':
				fallthrough
			case 'f':
				yyt4 = cursor
				goto yy56
			case 'H':
				fallthrough
			case 'h':
				yyt4 = cursor
				goto yy57
			case 'J':
				fallthrough
			case 'j':
				yyt4 = cursor
				goto yy58
			case 'K':
				fallthrough
			case 'k':
				yyt4 = cursor
				goto yy59
			case 'M':
				fallthrough
			case 'm':
				yyt4 = cursor
				goto yy60
			case 'N':
				fallthrough
			case 'n':
				yyt4 = cursor
				goto yy61
			case 'O':
				fallthrough
			case 'o':
				yyt4 = cursor
				goto yy62
			case 'S':
				fallthrough
			case 's':
				yyt4 = cursor
				goto yy63
			case 'T':
				fallthrough
			case 't':
				yyt4 = cursor
				goto yy64
			case 0xC5:
				yyt4 = cursor
				goto yy65
			default:
				goto yy19
			}
		yy19:
			cursor = marker
			goto yy2
		yy20:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy18
			default:
				goto yy19
			}
		yy21:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt2 = cursor
				goto yy18
			case '.':
				yyt2 = cursor
				goto yy20
			case 'N':
				fallthrough
			case 'R':
				fallthrough
			case 'n':
				fallthrough
			case 'r':
				yyt2 = cursor
				goto yy22
			case 'S':
				fallthrough
			case 's':
				yyt2 = cursor
				goto yy23
			case 'T':
				fallthrough
			case 't':
				yyt2 = cursor
				goto yy24
			default:
				goto yy19
			}
		yy22:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy20
			default:
				goto yy19
			}
		yy23:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy20
			default:
				goto yy19
			}
		yy24:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'H':
				fallthrough
			case 'h':
				goto yy20
			default:
				goto yy19
			}
		yy25:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy66
			default:
				goto yy19
			}
		yy26:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy67
			default:
				goto yy19
			}
		yy27:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy68
			default:
				goto yy19
			}
		yy28:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy69
			default:
				goto yy19
			}
		yy29:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'G':
				fallthrough
			case 'g':
				goto yy70
			default:
				goto yy19
			}
		yy30:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy71
			default:
				goto yy19
			}
		yy31:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x9E, 0x9F:
				goto yy72
			default:
				goto yy19
			}
		yy32:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'Z':
				fallthrough
			case 'c':
				fallthrough
			case 'z':
				goto yy73
			case 'S':
				fallthrough
			case 's':
				goto yy74
			default:
				goto yy19
			}
		yy33:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x89:
				fallthrough
			case 0xA9:
				goto yy75
			default:
				goto yy19
			}
		yy34:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy76
			default:
				goto yy19
			}
		yy35:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy77
			default:
				goto yy19
			}
		yy36:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy78
			default:
				goto yy19
			}
		yy37:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x89:
				fallthrough
			case 0xA9:
				goto yy79
			default:
				goto yy19
			}
		yy38:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'Z':
				fallthrough
			case 'z':
				goto yy80
			default:
				goto yy19
			}
		yy39:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy81
			default:
				goto yy19
			}
		yy40:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy82
			case 'L':
				fallthrough
			case 'l':
				goto yy83
			case 'N':
				fallthrough
			case 'n':
				goto yy84
			default:
				goto yy19
			}
		yy41:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x84:
				fallthrough
			case 0xA4:
				goto yy85
			default:
				goto yy19
			}
		yy42:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy86
			default:
				goto yy19
			}
		yy43:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy87
			case 'R':
				fallthrough
			case 'r':
				goto yy88
			case 'Y':
				fallthrough
			case 'y':
				goto yy89
			default:
				goto yy19
			}
		yy44:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy87
			default:
				goto yy19
			}
		yy45:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x84:
				fallthrough
			case 0xA4:
				goto yy90
			default:
				goto yy19
			}
		yy46:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy91
			default:
				goto yy19
			}
		yy47:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'V':
				fallthrough
			case 'v':
				goto yy92
			default:
				goto yy19
			}
		yy48:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy93
			case 'T':
				fallthrough
			case 't':
				goto yy94
			default:
				goto yy19
			}
		yy49:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy95
			default:
				goto yy19
			}
		yy50:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'P':
				fallthrough
			case 'p':
				goto yy96
			default:
				goto yy19
			}
		yy51:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy97
			default:
				goto yy19
			}
		yy52:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy98
			default:
				goto yy19
			}
		yy53:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'G':
				fallthrough
			case 'g':
				goto yy99
			case 'O':
				fallthrough
			case 'o':
				goto yy100
			case 'P':
				fallthrough
			case 'p':
				goto yy101
			case 'R':
				fallthrough
			case 'r':
				goto yy102
			case 'U':
				fallthrough
			case 'u':
				goto yy103
			case 'V':
				fallthrough
			case 'v':
				goto yy104
			case 0xC4:
				goto yy105
			default:
				goto yy19
			}
		yy54:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy106
			case 0xC3:
				goto yy107
			default:
				goto yy19
			}
		yy55:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'K':
				fallthrough
			case 'k':
				goto yy108
			case 'Y':
				fallthrough
			case 'y':
				goto yy109
			default:
				goto yy19
			}
		yy56:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy110
			case 0xC3:
				goto yy111
			default:
				goto yy19
			}
		yy57:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy112
			default:
				goto yy19
			}
		yy58:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy113
			case 'U':
				fallthrough
			case 'u':
				goto yy114
			case 0xC3:
				goto yy115
			default:
				goto yy19
			}
		yy59:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy116
			default:
				goto yy19
			}
		yy60:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy117
			case 'E':
				fallthrough
			case 'e':
				goto yy118
			case 0xC3:
				goto yy119
			default:
				goto yy19
			}
		yy61:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy120
			case 'O':
				fallthrough
			case 'o':
				goto yy121
			default:
				goto yy19
			}
		yy62:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy122
			case 'F':
				fallthrough
			case 'f':
				goto yy123
			case 'K':
				fallthrough
			case 'k':
				goto yy124
			default:
				goto yy19
			}
		yy63:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy125
			default:
				goto yy19
			}
		yy64:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy126
			default:
				goto yy19
			}
		yy65:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x9E, 0x9F:
				goto yy127
			default:
				goto yy19
			}
		yy66:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy128
			default:
				goto yy19
			}
		yy67:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy87
			default:
				goto yy19
			}
		yy68:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'I':
				fallthrough
			case 'i':
				goto yy130
			default:
				goto yy19
			}
		yy69:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'L':
				fallthrough
			case 'l':
				goto yy131
			default:
				goto yy19
			}
		yy70:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'U':
				fallthrough
			case 'u':
				goto yy132
			default:
				goto yy19
			}
		yy71:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy130
			default:
				goto yy19
			}
		yy72:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy133
			default:
				goto yy19
			}
		yy73:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'E':
				fallthrough
			case 'e':
				goto yy134
			default:
				goto yy19
			}
		yy74:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy134
			default:
				goto yy19
			}
		yy75:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy135
			default:
				goto yy19
			}
		yy76:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'M':
				fallthrough
			case 'm':
				goto yy87
			default:
				goto yy19
			}
		yy77:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 0xC3:
				goto yy136
			default:
				goto yy19
			}
		yy78:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'E':
				fallthrough
			case 'e':
				goto yy137
			case 'R':
				fallthrough
			case 'r':
				goto yy138
			default:
				goto yy19
			}
		yy79:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'V':
				fallthrough
			case 'v':
				goto yy139
			default:
				goto yy19
			}
		yy80:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'I':
				fallthrough
			case 'i':
				goto yy140
			default:
				goto yy19
			}
		yy81:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'U':
				fallthrough
			case 'u':
				goto yy141
			case 'V':
				fallthrough
			case 'v':
				goto yy142
			default:
				goto yy19
			}
		yy82:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy143
			case 'N':
				fallthrough
			case 'n':
				goto yy87
			default:
				goto yy19
			}
		yy83:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'I':
				fallthrough
			case 'Y':
				fallthrough
			case 'i':
				fallthrough
			case 'y':
				goto yy87
			default:
				goto yy19
			}
		yy84:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'E':
				fallthrough
			case 'I':
				fallthrough
			case 'e':
				fallthrough
			case 'i':
				goto yy87
			default:
				goto yy19
			}
		yy85:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy144
			default:
				goto yy19
			}
		yy86:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'I':
				goto yy145
			case 0xC4:
				goto yy146
			default:
				goto yy19
			}
		yy87:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			default:
				goto yy19
			}
		yy88:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'C':
				fallthrough
			case 'c':
				goto yy147
			case 'E':
				fallthrough
			case 'e':
				goto yy67
			case 'S', 'T':
				fallthrough
			case 's', 't':
				goto yy87
			default:
				goto yy19
			}
		yy89:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'I':
				goto yy148
			case 0xC4:
				goto yy149
			default:
				goto yy19
			}
		yy90:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy150
			default:
				goto yy19
			}
		yy91:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'A':
				fallthrough
			case 'a':
				goto yy151
			default:
				goto yy19
			}
		yy92:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'E':
				fallthrough
			case 'e':
				goto yy152
			default:
				goto yy19
			}
		yy93:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'K':
				fallthrough
			case 'k':
				goto yy87
			default:
				goto yy19
			}
		yy94:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'O':
				fallthrough
			case 'o':
				goto yy153
			default:
				goto yy19
			}
		yy95:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'O':
				fallthrough
			case 'o':
				goto yy154
			default:
				goto yy19
			}
		yy96:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'T':
				fallthrough
			case 't':
				goto yy155
			default:
				goto yy19
			}
		yy97:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'M':
				fallthrough
			case 'm':
				goto yy156
			default:
				goto yy19
			}
		yy98:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy157
			default:
				goto yy19
			}
		yy99:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy158
			default:
				goto yy19
			}
		yy100:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy159
			default:
				goto yy19
			}
		yy101:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy160
			default:
				goto yy19
			}
		yy102:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy161
			default:
				goto yy19
			}
		yy103:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'G':
				fallthrough
			case 'g':
				goto yy162
			default:
				goto yy19
			}
		yy104:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy163
			default:
				goto yy19
			}
		yy105:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x9E, 0x9F:
				goto yy164
			default:
				goto yy19
			}
		yy106:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'Z':
				fallthrough
			case 'c':
				fallthrough
			case 'z':
				goto yy165
			case 'S':
				fallthrough
			case 's':
				goto yy166
			default:
				goto yy19
			}
		yy107:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x89:
				fallthrough
			case 0xA9:
				goto yy167
			default:
				goto yy19
			}
		yy108:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy168
			default:
				goto yy19
			}
		yy109:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy169
			default:
				goto yy19
			}
		yy110:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy170
			default:
				goto yy19
			}
		yy111:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x89:
				fallthrough
			case 0xA9:
				goto yy171
			default:
				goto yy19
			}
		yy112:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'Z':
				fallthrough
			case 'z':
				goto yy172
			default:
				goto yy19
			}
		yy113:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy173
			default:
				goto yy19
			}
		yy114:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy174
			case 'L':
				fallthrough
			case 'l':
				goto yy175
			case 'N':
				fallthrough
			case 'n':
				goto yy176
			default:
				goto yy19
			}
		yy115:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x84:
				fallthrough
			case 0xA4:
				goto yy177
			default:
				goto yy19
			}
		yy116:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy178
			default:
				goto yy19
			}
		yy117:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy179
			case 'R':
				fallthrough
			case 'r':
				goto yy180
			case 'Y':
				fallthrough
			case 'y':
				goto yy181
			default:
				goto yy19
			}
		yy118:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy179
			default:
				goto yy19
			}
		yy119:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x84:
				fallthrough
			case 0xA4:
				goto yy182
			default:
				goto yy19
			}
		yy120:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy183
			default:
				goto yy19
			}
		yy121:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'V':
				fallthrough
			case 'v':
				goto yy184
			default:
				goto yy19
			}
		yy122:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy185
			case 'T':
				fallthrough
			case 't':
				goto yy186
			default:
				goto yy19
			}
		yy123:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy187
			default:
				goto yy19
			}
		yy124:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy188
			default:
				goto yy19
			}
		yy125:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'P':
				fallthrough
			case 'p':
				goto yy189
			default:
				goto yy19
			}
		yy126:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy190
			default:
				goto yy19
			}
		yy127:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy191
			default:
				goto yy19
			}
		yy128:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy192
			default:
				goto yy19
			}
		yy129:
			cursor++
			yych = input[cursor]
			switch yych {
			case '0', '1', '2', '3':
				yyt2 = cursor
				goto yy193
			case '4', '5', '6', '7', '8', '9':
				yyt2 = cursor
				goto yy194
			default:
				goto yy19
			}
		yy130:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy87
			default:
				goto yy19
			}
		yy131:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				goto yy195
			case 0xC4:
				goto yy196
			default:
				goto yy19
			}
		yy132:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy67
			default:
				goto yy19
			}
		yy133:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'S':
				fallthrough
			case 's':
				goto yy197
			default:
				goto yy19
			}
		yy134:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy154
			default:
				goto yy19
			}
		yy135:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy198
			default:
				goto yy19
			}
		yy136:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x9C:
				fallthrough
			case 0xBC:
				goto yy130
			default:
				goto yy19
			}
		yy137:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy87
			default:
				goto yy19
			}
		yy138:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy141
			default:
				goto yy19
			}
		yy139:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy142
			default:
				goto yy19
			}
		yy140:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy199
			default:
				goto yy19
			}
		yy141:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy200
			default:
				goto yy19
			}
		yy142:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy201
			default:
				goto yy19
			}
		yy143:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy202
			default:
				goto yy19
			}
		yy144:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy201
			default:
				goto yy19
			}
		yy145:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy87
			default:
				goto yy19
			}
		yy146:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0xB1:
				goto yy145
			default:
				goto yy19
			}
		yy147:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'H':
				fallthrough
			case 'h':
				goto yy87
			default:
				goto yy19
			}
		yy148:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy87
			default:
				goto yy19
			}
		yy149:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0xB1:
				goto yy148
			default:
				goto yy19
			}
		yy150:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'Z':
				fallthrough
			case 'z':
				goto yy87
			default:
				goto yy19
			}
		yy151:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy87
			default:
				goto yy19
			}
		yy152:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy153
			default:
				goto yy19
			}
		yy153:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy203
			default:
				goto yy19
			}
		yy154:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy201
			default:
				goto yy19
			}
		yy155:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy152
			default:
				goto yy19
			}
		yy156:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy204
			default:
				goto yy19
			}
		yy157:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy129
			case 'A':
				fallthrough
			case 'a':
				goto yy67
			default:
				goto yy19
			}
		yy158:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy205
			default:
				goto yy19
			}
		yy159:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy179
			default:
				goto yy19
			}
		yy160:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'I':
				fallthrough
			case 'i':
				goto yy208
			default:
				goto yy19
			}
		yy161:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'L':
				fallthrough
			case 'l':
				goto yy209
			default:
				goto yy19
			}
		yy162:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'U':
				fallthrough
			case 'u':
				goto yy210
			default:
				goto yy19
			}
		yy163:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy208
			default:
				goto yy19
			}
		yy164:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy211
			default:
				goto yy19
			}
		yy165:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'E':
				fallthrough
			case 'e':
				goto yy212
			default:
				goto yy19
			}
		yy166:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy212
			default:
				goto yy19
			}
		yy167:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy213
			default:
				goto yy19
			}
		yy168:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'M':
				fallthrough
			case 'm':
				goto yy179
			default:
				goto yy19
			}
		yy169:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 0xC3:
				goto yy214
			default:
				goto yy19
			}
		yy170:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'E':
				fallthrough
			case 'e':
				goto yy215
			case 'R':
				fallthrough
			case 'r':
				goto yy216
			default:
				goto yy19
			}
		yy171:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'V':
				fallthrough
			case 'v':
				goto yy217
			default:
				goto yy19
			}
		yy172:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'I':
				fallthrough
			case 'i':
				goto yy218
			default:
				goto yy19
			}
		yy173:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'U':
				fallthrough
			case 'u':
				goto yy219
			case 'V':
				fallthrough
			case 'v':
				goto yy220
			default:
				goto yy19
			}
		yy174:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy221
			case 'N':
				fallthrough
			case 'n':
				goto yy179
			default:
				goto yy19
			}
		yy175:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'I':
				fallthrough
			case 'Y':
				fallthrough
			case 'i':
				fallthrough
			case 'y':
				goto yy179
			default:
				goto yy19
			}
		yy176:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'E':
				fallthrough
			case 'I':
				fallthrough
			case 'e':
				fallthrough
			case 'i':
				goto yy179
			default:
				goto yy19
			}
		yy177:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy222
			default:
				goto yy19
			}
		yy178:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'I':
				goto yy223
			case 0xC4:
				goto yy224
			default:
				goto yy19
			}
		yy179:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			default:
				goto yy19
			}
		yy180:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'C':
				fallthrough
			case 'c':
				goto yy225
			case 'E':
				fallthrough
			case 'e':
				goto yy159
			case 'S', 'T':
				fallthrough
			case 's', 't':
				goto yy179
			default:
				goto yy19
			}
		yy181:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'I':
				goto yy226
			case 0xC4:
				goto yy227
			default:
				goto yy19
			}
		yy182:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy228
			default:
				goto yy19
			}
		yy183:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'A':
				fallthrough
			case 'a':
				goto yy229
			default:
				goto yy19
			}
		yy184:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'E':
				fallthrough
			case 'e':
				goto yy230
			default:
				goto yy19
			}
		yy185:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'K':
				fallthrough
			case 'k':
				goto yy179
			default:
				goto yy19
			}
		yy186:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'O':
				fallthrough
			case 'o':
				goto yy231
			default:
				goto yy19
			}
		yy187:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				yyt4 = cursor
				goto yy53
			case 'D':
				fallthrough
			case 'd':
				yyt4 = cursor
				goto yy54
			case 'E':
				fallthrough
			case 'e':
				yyt4 = cursor
				goto yy55
			case 'F':
				fallthrough
			case 'f':
				yyt4 = cursor
				goto yy56
			case 'H':
				fallthrough
			case 'h':
				yyt4 = cursor
				goto yy57
			case 'J':
				fallthrough
			case 'j':
				yyt4 = cursor
				goto yy58
			case 'K':
				fallthrough
			case 'k':
				yyt4 = cursor
				goto yy59
			case 'M':
				fallthrough
			case 'm':
				yyt4 = cursor
				goto yy60
			case 'N':
				fallthrough
			case 'n':
				yyt4 = cursor
				goto yy61
			case 'O':
				fallthrough
			case 'o':
				yyt4 = cursor
				goto yy232
			case 'S':
				fallthrough
			case 's':
				yyt4 = cursor
				goto yy63
			case 'T':
				fallthrough
			case 't':
				yyt4 = cursor
				goto yy64
			case 0xC5:
				yyt4 = cursor
				goto yy65
			default:
				goto yy19
			}
		yy188:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'O':
				fallthrough
			case 'o':
				goto yy233
			default:
				goto yy19
			}
		yy189:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'T':
				fallthrough
			case 't':
				goto yy234
			default:
				goto yy19
			}
		yy190:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'M':
				fallthrough
			case 'm':
				goto yy235
			default:
				goto yy19
			}
		yy191:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy236
			default:
				goto yy19
			}
		yy192:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy148
			default:
				goto yy19
			}
		yy193:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy237
			case ',':
				yyt3 = cursor
				goto yy238
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy194
			case 'N':
				fallthrough
			case 'R':
				fallthrough
			case 'n':
				fallthrough
			case 'r':
				yyt3 = cursor
				goto yy239
			case 'S':
				fallthrough
			case 's':
				yyt3 = cursor
				goto yy240
			case 'T':
				fallthrough
			case 't':
				yyt3 = cursor
				goto yy241
			default:
				goto yy19
			}
		yy194:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy237
			case ',':
				yyt3 = cursor
				goto yy238
			case 'N':
				fallthrough
			case 'R':
				fallthrough
			case 'n':
				fallthrough
			case 'r':
				yyt3 = cursor
				goto yy239
			case 'S':
				fallthrough
			case 's':
				yyt3 = cursor
				goto yy240
			case 'T':
				fallthrough
			case 't':
				yyt3 = cursor
				goto yy241
			default:
				goto yy19
			}
		yy195:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'K':
				fallthrough
			case 'k':
				goto yy87
			default:
				goto yy19
			}
		yy196:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0xB1:
				goto yy195
			default:
				goto yy19
			}
		yy197:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy242
			default:
				goto yy19
			}
		yy198:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy243
			default:
				goto yy19
			}
		yy199:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy151
			default:
				goto yy19
			}
		yy200:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy83
			default:
				goto yy19
			}
		yy201:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy137
			default:
				goto yy19
			}
		yy202:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy67
			default:
				goto yy19
			}
		yy203:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy137
			case 'R':
				fallthrough
			case 'r':
				goto yy244
			default:
				goto yy19
			}
		yy204:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'Z':
				fallthrough
			case 'z':
				goto yy87
			default:
				goto yy19
			}
		yy205:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy245
			default:
				goto yy19
			}
		yy206:
			cursor++
			yych = input[cursor]
			switch yych {
			case '1':
				goto yy246
			case '2':
				goto yy247
			default:
				goto yy19
			}
		yy207:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy206
			default:
				goto yy19
			}
		yy208:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy179
			default:
				goto yy19
			}
		yy209:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				goto yy248
			case 0xC4:
				goto yy249
			default:
				goto yy19
			}
		yy210:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy159
			default:
				goto yy19
			}
		yy211:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'S':
				fallthrough
			case 's':
				goto yy250
			default:
				goto yy19
			}
		yy212:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy233
			default:
				goto yy19
			}
		yy213:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy251
			default:
				goto yy19
			}
		yy214:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x9C:
				fallthrough
			case 0xBC:
				goto yy208
			default:
				goto yy19
			}
		yy215:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy179
			default:
				goto yy19
			}
		yy216:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy219
			default:
				goto yy19
			}
		yy217:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy220
			default:
				goto yy19
			}
		yy218:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy252
			default:
				goto yy19
			}
		yy219:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy253
			default:
				goto yy19
			}
		yy220:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy254
			default:
				goto yy19
			}
		yy221:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy255
			default:
				goto yy19
			}
		yy222:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy254
			default:
				goto yy19
			}
		yy223:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy179
			default:
				goto yy19
			}
		yy224:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0xB1:
				goto yy223
			default:
				goto yy19
			}
		yy225:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'H':
				fallthrough
			case 'h':
				goto yy179
			default:
				goto yy19
			}
		yy226:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy179
			default:
				goto yy19
			}
		yy227:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0xB1:
				goto yy226
			default:
				goto yy19
			}
		yy228:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'Z':
				fallthrough
			case 'z':
				goto yy179
			default:
				goto yy19
			}
		yy229:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy179
			default:
				goto yy19
			}
		yy230:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy231
			default:
				goto yy19
			}
		yy231:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy256
			default:
				goto yy19
			}
		yy232:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy122
			case 'K':
				fallthrough
			case 'k':
				goto yy124
			default:
				goto yy19
			}
		yy233:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy254
			default:
				goto yy19
			}
		yy234:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy230
			default:
				goto yy19
			}
		yy235:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy257
			default:
				goto yy19
			}
		yy236:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt3 = cursor
				goto yy206
			case ',':
				fallthrough
			case '.':
				yyt3 = cursor
				goto yy207
			case 'A':
				fallthrough
			case 'a':
				goto yy159
			default:
				goto yy19
			}
		yy237:
			cursor++
			yych = input[cursor]
			switch yych {
			case '1':
				goto yy258
			case '2':
				goto yy259
			default:
				goto yy19
			}
		yy238:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy237
			default:
				goto yy19
			}
		yy239:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy260
			default:
				goto yy19
			}
		yy240:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy260
			default:
				goto yy19
			}
		yy241:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'H':
				fallthrough
			case 'h':
				goto yy260
			default:
				goto yy19
			}
		yy242:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy148
			default:
				goto yy19
			}
		yy243:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy261
			default:
				goto yy19
			}
		yy244:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy87
			default:
				goto yy19
			}
		yy245:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy226
			default:
				goto yy19
			}
		yy246:
			cursor++
			yych = input[cursor]
			switch yych {
			case '9':
				goto yy262
			default:
				goto yy19
			}
		yy247:
			cursor++
			yych = input[cursor]
			switch yych {
			case '0':
				goto yy263
			default:
				goto yy19
			}
		yy248:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'K':
				fallthrough
			case 'k':
				goto yy179
			default:
				goto yy19
			}
		yy249:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0xB1:
				goto yy248
			default:
				goto yy19
			}
		yy250:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy264
			default:
				goto yy19
			}
		yy251:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy265
			default:
				goto yy19
			}
		yy252:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy229
			default:
				goto yy19
			}
		yy253:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy175
			default:
				goto yy19
			}
		yy254:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy215
			default:
				goto yy19
			}
		yy255:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy159
			default:
				goto yy19
			}
		yy256:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy215
			case 'R':
				fallthrough
			case 'r':
				goto yy266
			default:
				goto yy19
			}
		yy257:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'Z':
				fallthrough
			case 'z':
				goto yy179
			default:
				goto yy19
			}
		yy258:
			cursor++
			yych = input[cursor]
			switch yych {
			case '9':
				goto yy267
			default:
				goto yy19
			}
		yy259:
			cursor++
			yych = input[cursor]
			switch yych {
			case '0':
				goto yy268
			default:
				goto yy19
			}
		yy260:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy237
			case ',':
				goto yy238
			default:
				goto yy19
			}
		yy261:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy244
			default:
				goto yy19
			}
		yy262:
			cursor++
			yych = input[cursor]
			switch yych {
			case '9':
				goto yy269
			default:
				goto yy19
			}
		yy263:
			cursor++
			yych = input[cursor]
			switch yych {
			case '0', '1', '2', '3':
				goto yy269
			default:
				goto yy19
			}
		yy264:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy226
			default:
				goto yy19
			}
		yy265:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy270
			default:
				goto yy19
			}
		yy266:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy179
			default:
				goto yy19
			}
		yy267:
			cursor++
			yych = input[cursor]
			switch yych {
			case '9':
				goto yy271
			default:
				goto yy19
			}
		yy268:
			cursor++
			yych = input[cursor]
			switch yych {
			case '0', '1', '2', '3':
				goto yy271
			default:
				goto yy19
			}
		yy269:
			cursor++
			yych = input[cursor]
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy272
			default:
				goto yy19
			}
		yy270:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy266
			default:
				goto yy19
			}
		yy271:
			cursor++
			yych = input[cursor]
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy273
			default:
				goto yy19
			}
		yy272:
			cursor++
			yynmatch = 4
			yypmatch[2] = yyt1
			yypmatch[3] = yyt2
			yypmatch[4] = yyt4
			yypmatch[5] = yyt3
			yypmatch[0] = yyt1
			yypmatch[1] = cursor
			yypmatch[6] = cursor
			yypmatch[6] += -4
			yypmatch[7] = cursor
			{
				day = input[yypmatch[2]:yypmatch[3]]
				month = input[yypmatch[4]:yypmatch[5]]
				year = input[yypmatch[6]:yypmatch[7]]
				ok = true
				return
			}
		yy273:
			cursor++
			yynmatch = 4
			yypmatch[2] = yyt1
			yypmatch[4] = yyt2
			yypmatch[5] = yyt3
			yypmatch[0] = yyt1
			yypmatch[1] = cursor
			yypmatch[3] = yyt2
			yypmatch[3] += -1
			yypmatch[6] = cursor
			yypmatch[6] += -4
			yypmatch[7] = cursor
			{
				month = input[yypmatch[2]:yypmatch[3]]
				day = input[yypmatch[4]:yypmatch[5]]
				year = input[yypmatch[6]:yypmatch[7]]
				ok = true
				return
			}
		yy274:
			{
				return
			}
		}

	}
}
